"""Builds a diagnostic report safe to share with anyone helping debug -
`movie-planner bug-report` (issue #256). Never includes CalDAV
credentials, API keys, entry titles/notes, or venue names; those are
exactly the fields flagged as PII when this was scoped, so they're
either dropped entirely (secrets) or reduced to a count (personal entry
data) rather than guessed at case by case. Ratings/dates/genres stay in,
since the report is otherwise not useful for diagnosing a real bug.
"""

import platform
from collections import Counter
from importlib.metadata import version

from movie_planner.config import Config
from movie_planner.store import Store


def build_bug_report(cfg: Config, store: Store) -> str:
    entries = store.list_entries()
    media_names = {m.id: m.name for m in store.list_media()}
    venues = store.list_venues()
    activity = store.list_activity()
    import_failures = store.list_import_failures()

    medium_counts = Counter(media_names.get(e.medium_id, "unknown") for e in entries)
    dates = [e.date for e in entries]
    activity_counts = Counter(a.action for a in activity)

    lines = [
        "# movie-planner bug report",
        "",
        "Generated by `movie-planner bug-report`. Config secrets, entry",
        "titles/notes, and venue names are never included - see",
        "https://github.com/alrayyes/movie-planner/issues/256 for what's",
        "in scope and why.",
        "",
        "## Environment",
        f"- movie-planner: {version('movie-planner')}",
        f"- Python: {platform.python_version()}",
        f"- Platform: {platform.platform()}",
        "",
        "## Config shape",
        "- caldav: configured",
        "- omdb: configured",
        f"- tmdb: {'configured' if cfg.tmdb_api_key else 'not configured'}",
        "",
        "## Store",
        f"- entries: {len(entries)}",
        f"- date range: {min(dates).isoformat() if dates else 'n/a'} to "
        f"{max(dates).isoformat() if dates else 'n/a'}",
        f"- media: {dict(sorted(medium_counts.items()))}",
        f"- venues: {len(venues)}",
        f"- entries with notes: {sum(1 for e in entries if e.notes)}",
        "",
        "## Activity log",
        f"- create: {activity_counts.get('create', 0)}",
        f"- update: {activity_counts.get('update', 0)}",
        f"- delete: {activity_counts.get('delete', 0)}",
        "",
        "## Import failures",
        f"- count: {len(import_failures)}",
    ]
    return "\n".join(lines) + "\n"
